#pragma once

#define NON_TERMINAL_LIST \
    X(PROGRAMA)\
    X(BLOQUE)\
    X(AREA_VARIABLES)\
    X(AREA_SUBRUTINAS)\
    X(FUNCION)\
    X(PROCEDIMIENTO)\
    X(PARAMETROS_FORMALES)\
    X(PARAMETRO_FORMAL)\
    X(PARAMETRO_FORMAL1)\
    X(PARAMETROS_ACTUALES)\
    X(SUBRUTINA)\
    X(LISTA_DECLARACION_VARIABLES)\
    X(LISTA_EXPRESIONES)\
    X(LISTA_FACTORES)\
    X(LISTA_IDENTIFICADORES)\
    X(LISTA_PARAMETROS_FORMALES)\
    X(LISTA_SENTENCIAS)\
    X(LISTA_TERMINOS)\
    X(SENTENCIA)\
    X(SENTENCIA_COMPUESTA)\
    X(SENTENCIA_CONDICIONAL)\
    X(SENTENCIA_ELSE)\
    X(SENTENCIA_REPETITIVA)\
    X(SENTENCIA_SIMPLE)\
    X(SENTENCIA_SIMPLE1)\
    X(EXPRESION)\
    X(EXPRESION1)\
    X(EXPRESION_SIMPLE)\
    X(FACTOR)\
    X(FACTOR1)\
    X(DATA_TYPE)\
    X(TERMINO)\
    X(OPERADOR_FACTORES)\
    X(OPERADOR_TERMINOS)

enum class non_terminal 
{
    #define X(name) name,
    NON_TERMINAL_LIST
    #undef X
};